name: Test GH_TOKEN Issue Creator

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

jobs:
  create-and-close-issue:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this automatically
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run script to create and close issue
        run: python manage_issue.py
