name: Test GH_TOKEN Issue Creator

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

permissions:
  issues: write
  contents: read
  
jobs:
  create-and-close-issue:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}  # GitHub provides this automatically
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run script to create and close issue
        run: python manage_issue.py

      - name: Trigger second workflow
        if: success()   # ✅ Runs only if script exits with 0
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ env.GH_TOKEN }}
          repository: ${{ env.GITHUB_REPOSITORY }}
          event-type: issue-closed-automation
